branches:
  only:
    - master

sudo: required

language: ruby

services:
- docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - IMAGE=metricmike/simrep
    - IMAGE_VERSION=$IMAGE:$COMMIT

before_script:
  # - docker build -t $IMAGE:$COMMIT app
  # - docker tag $IMAGE:$COMMIT $IMAGE:latest
  # - docker tag $IMAGE:$COMMIT $IMAGE:travis-$TRAVIS_BUILD_NUMBER

script:
  - docker version
  - docker-compose version
  - docker-compose up -d
  - docker ps -a
  - docker-compose run --rm web rspec spec/
  # - docker-compose -f docker-compose.ci.yml run test

# after_success:
#   - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" registry.heroku.com
#   - docker push $IMAGE
#   - curl https://sdk.cloud.google.com | bash
#   - source /home/travis/.bashrc
