version: 2
executorType: machine

stages:
  build:
    workDir: ~/simrep
    steps:
      - type: checkout
      - type: shell
        name: Build Project
        command: |
          docker --version
          docker-compose --version
          docker-compose up -d
      - type: shell
        name: Ping SimRep
        command: |
          curl -I localhost:3000
