version: 2
executorType: machine

stages:
  build:
    workDir: ~/simrep
    environment:
      - ENV_FILE: ".ci.env"
    steps:
      - type: checkout

      - type: shell
        name: Upgrade Docker & Docker Compose
        command: |
          sudo apt-get update
          sudo apt-get -y install docker-engine
          pip install docker-compose
          docker --version
          docker-compose --version

      - type: shell
        name: Login to Docker Hub and Pull
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker pull metricmike/simrep:base

      - type: shell
        name: Build SimRep
        command: |
          docker-compose up -d

      - type: shell
        name: Test SimRep
        command: |
          docker-compose run -e RAILS_ENV=test web bash ./bin/start_test
