version: 2
executorType: machine

stages:
  build:
    workDir: ~/simrep
    steps:
      - type: checkout
      - type: shell
        name: Upgrade Docker
        command: |
          sudo apt-get update
          sudo apt-get -y install docker-engine
      - type: shell
        name: Upgrade Docker-Compose
        command: |
          pip install docker-compose
      - type: shell
        name: Check Docker Version
        command: |
          docker --version
          docker-compose --version

      - type: shell
        name: Build SimRep
        command: |
          docker-compose -f docker-compose.ci.yml up -d
          docker-compose -f docker-compose.ci.yml run --rm web rails db:setup
      - type: shell
        name: Test SimRep
        command: |
          docker-compose -f docker-compose.ci.yml run --rm -e RAILS_ENV=test web rspec spec/

      - type: shell
        name: Ping SimRep
        command: |
          curl localhost:3000

      - type: shell
        name: Push SimRep image
        command: |
          docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
          docker push simrep/build-image:2.0.0