version: 2
executorType: machine

stages:
  build:
    workDir: ~/simrep
    steps:
      - type: checkout
      - type: shell
        name: Check Docker Version
        command: |
          docker --version
          docker-compose --version
      - type: shell
        name: Upgrade Docker
        command: |
          sudo apt-get update
          sudo apt-get -y install docker-engine
      - type: shell
        name: Check Docker Version
        command: |
          docker --version
          docker-compose --version

      #     docker-compose -f docker-compose.ci.yml up -d
      # - type: shell
      #   name: Ping SimRep
      #   command: |
      #     curl -I localhost:3000
