version: 2
executorType: machine

stages:
  build:
    workDir: ~/simrep
    steps:
      - type: checkout

      - type: shell
        name: Upgrade Docker
        command: |
          sudo apt-get update
          sudo apt-get -y install docker-engine
      - type: shell
        name: Upgrade Docker-Compose
        command: |
          pip install docker-compose
      - type: shell
        name: Check Docker Version
        command: |
          docker --version
          docker-compose --version

      - type: shell
        name: Build SimRep
        command: |
          docker build -t simrep:build .
          docker-compose -f docker-compose.ci.yml up -d

      - type: shell
        name: Test SimRep
        command: |
          docker-compose -f docker-compose.ci.yml run -e RAILS_ENV=test web bash ./bin/start_test

      - type: shell
        name: Push SimRep image
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          VERSION=$(docker-compose run web rails runner "puts SimRep::Application::Version")
          docker tag $(docker images -q simrep:build) metricmike/simrep:$VERSION
          docker push metricmike/simrep:$VERSION