version: 2
executorType: machine

stages:
  build:
    workDir: ~/simrep
    environment:
      - ENV_FILE: ".ci.env"
    steps:
      - type: checkout

      - type: shell
        name: Prep VM (PG Off, Docker Updates)
        command: |
          sudo service postgresql stop
          sudo apt-get update
          sudo apt-get -y install docker-engine
          pip install docker-compose
          docker --version
          docker-compose --version

      - type: shell
        name: Login to Docker Hub, Build, and Push
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -t metricmike/simrep:1.1.1 .
          docker push metricmike/simrep:1.1.1

      - type: shell
        name: Build SimRep
        command: |
          cd docker
          docker-compose up -d

      - type: shell
        name: Test SimRep
        command: |
          cd docker
          docker-compose run -e RAILS_ENV=test web bash ./bin/start_test
          docker-compose run -e RAILS_ENV=test web codeclimate-test-reporter
