version: '2'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: simrep
      POSTGRES_PASSWORD: simrep
    expose:
      - '5432'
    volumes:
      - vol-postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    expose:
      - '6379'
    volumes:
      - vol-redis:/var/lib/redis/data

  web:
    depends_on:
      - postgres
      - redis
    build: .
    image: metricmike/simrep
    command: ./bin/start_web
    volumes:
      - .:/var/www/simrep
      - vol-bundle:/usr/local/bundle
    ports:
      - '3000:3000'
    env_file:
      - .ci.env

  # Add an nginx reverse-proxy

  worker:
    depends_on:
      - postgres
      - redis
      - web # Because web is responsible for bundle install and precompile if necessary
    image: metricmike/simrep
    command: ./bin/start_worker
    volumes:
      - .:/var/www/simrep
      - vol-bundle:/usr/local/bundle
    env_file:
      - .ci.env

volumes:
  vol-postgres:
  vol-redis:
  vol-bundle:
