version: '2'

services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: simrep
      POSTGRES_PASSWORD: simrep
    ports:
      - '5432:5432'
    volumes:
      - vol-postgres:/var/lib/postgresql/data

  redis-cache:
    image: redis:3.2-alpine
    expose:
      - '6379'
    volumes:
      - vol-redis-cache:/var/lib/redis/data

  redis-session:
    image: redis:3.2-alpine
    expose:
      - '6379'
    volumes:
      - vol-redis-session:/var/lib/redis/data

  redis-metastore:
    image: redis:3.2-alpine
    expose:
      - '6379'
    volumes:
      - vol-redis-metastore:/var/lib/redis/data

  redis-entitystore:
    image: redis:3.2-alpine
    expose:
      - '6379'
    volumes:
      - vol-redis-entitystore:/var/lib/redis/data

  redis-worker:
    image: redis:3.2-alpine
    expose:
      - '6379'
    volumes:
      - vol-redis-worker:/var/lib/redis/data

  web:
    tty: true
    stdin_open: true
    depends_on:
      - postgres
      - redis-cache
      - redis-session
      - redis-metastore
      - redis-entitystore
    build: .
    command: ./bin/start_web
    volumes:
      - .:/var/www/simrep
      - vol-bundle:/usr/local/bundle
    ports:
      - '3000:3000'
    env_file:
      - .simrep.env

  # Add an nginx reverse-proxy

  worker:
    depends_on:
      - postgres
      - web # Because web is responsible for bundle install and precompile if necessary
      - redis-worker
    build: .
    command: ./bin/start_worker
    volumes:
      - .:/var/www/simrep
      - vol-bundle:/usr/local/bundle
    env_file:
      - .simrep.env
volumes:
  vol-redis-cache:
  vol-redis-session:
  vol-redis-metastore:
  vol-redis-entitystore:
  vol-redis-worker:
  vol-postgres:
  vol-bundle:
