version: 2
jobs:
  build:
    machine:
      enabled: true
    workDir: ~/simrep
    environment:
      - ENV_FILE: ".ci.env"
    steps:
      - checkout

      - run:
          name: Prep VM (PG Off, Docker Updates)
          command: |
            sudo service postgresql stop
            sudo apt-get update
            sudo apt-get -y install docker-engine
            pip install docker-compose
            docker --version
            docker-compose --version

      - run:
          name: Login to Docker Hub and Pull
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker pull metricmike/simrep:1.1.1

      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "Gemfile.lock" }}

      - run:
          name: Build SimRep
          command: |
            cd docker
            docker-compose up -d
            docker-compose logs -t app
            sleep 120
            docker-compose logs -t app
            sleep 120
            docker-compose logs -t app
            sleep 120

      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - "${BUNDLE_PATH}"

      - run:
          name: Test SimRep
          command: |
            cd docker
            whoami
            ls -lah ..
            ls -lah ../coverage
            docker-compose run app bash ./bin/start_test
            docker-compose run app codeclimate-test-reporter
