version: 2
jobs:
  build:
    docker:
      - image: amidos/dcind
      - image: postgres:9.6-alpine
      - image: redis:3.2-alpine
      - image: nginx:1.11-alpine
      - image: metricmike/simrep:1.1.1
    working_directory: ~/simrep
    environment:
      - ENV_FILE: ".ci.env"
    steps:
      - run:
          name: Prep Environment
          command: |
            apk add git
            git --version
            docker --version
            docker-compose --version

      - checkout

      - setup_docker_engine

      - run:
          name: Login to Docker Hub and Pull
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker pull metricmike/simrep:1.1.1

      # - restore_cache:
      #     key: dependency-cache-{{ .Branch }}-{{ checksum "Gemfile.lock" }}

      - run:
          name: Build SimRep
          command: |
            cd docker
            docker-compose up -d
            docker-compose logs -t app
            sleep 120
            docker-compose logs -t app
            sleep 120
            docker-compose logs -t app
            sleep 120

      # - save_cache:
      #     key: dependency-cache-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      #     paths:
      #       - "${BUNDLE_PATH}"

      - run:
          name: Test SimRep
          command: |
            cd docker
            docker-compose run app bash ./bin/start_test
            docker-compose run app codeclimate-test-reporter
