version: '3'

services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: simrep
      POSTGRES_PASSWORD: simrep
    ports:
      - 5432:5432
    volumes:
      - vol-postgres:/var/lib/postgresql/data

  redis-worker:
    image: redis:4.0-alpine
    ports:
      - 6379:6379
    command: "redis-server --save '' --appendonly no"

  athena:
    image: arachnysdocker/athenapdf-service:2
    environment:
      GIN_MODE: "debug"
      WEAVER_AUTH_KEY: "arachnys-weaver"
      WEAVER_ATHENA_CMD: "athenapdf -S"
      WEAVER_MAX_WORKERS: "10"
      WEAVER_MAX_CONVERSION_QUEUE: "50"
      WEAVER_WORKER_TIMEOUT: "90"
      WEAVER_CONVERSION_FALLBACK: "false"
    ports:
      - 8080:8080

volumes:
  vol-postgres:
