common: &default_settings
  license_key: <%= ENV['NEW_RELIC_LICENSE_KEY'] %>
  app_name: SimRep (<%= ENV['RAILS_ENV'] %>)
  log_level: info
  capture_params: true

development:
  <<: *default_settings
  developer_mode: true

test:
  <<: *default_settings
  monitor_mode: false

staging:
  <<: *default_settings

production:
  <<: *default_settings